server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://10.112.121.163:3306/aptsmas?characterEncoding=utf-8
    username: root
    password: limeMySql8
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
