server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aptsmas?characterEncoding=utf-8
    username: root
    password: zhangyun
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
